### PR TITLE
Redesign button layout

### PR DESCRIPTION
**Pull request by reece-bennett**
Make new button layout as discussed in #16

### CODE REVIEW

**Comment by MohitChattlani** [comment]
Please make the calculator look good on mobiles. You can use chrome dev tools to test it. Rest is fine.

**Comment by reece-bennett** [comment]
What did you mean exactly? Looks fine to me on Chrome for Android:

**Comment by MohitChattlani** [comment]
let me recheck @PhyscoKillerMonkey

**Comment by MohitChattlani** [comment]
the layout of the entire calculator shifts to the left when I do more and more computations. here is a look.
err1

**Comment by reece-bennett** [comment]
Should be fixed: 

image

**Pull request merged**
