### PR TITLE
Mapped number pad keycodes and made them functional. 

### LINKED ISSUE #4: To add number keys functionality in calculator so that keyboard can also be used for inputs.

### PR DESCRIPTION
**Pull request by eclecticexistential**
1-9, /,*,-,+, escape, and enter functionality added.

Fixes #4

### CODE REVIEW

**Comment by MohitChattlani** [comment]
I would personally like to use the numeric keypad of the keyboard instead of the above keys. Please change the number keys i.e ( 0-9 keys )  so that I am able to use the numeric keypad for calculations. Rest is fine.

**Comment by eclecticexistential** [comment]
Both the top row of the keyboard and the number pad should be functional.
I am using Chrome to test this.

**Comment by MohitChattlani** [comment]
Let me recheck.

**Comment by MohitChattlani** [comment]
So it is working right. there is another issue that just popped up. When pressing keys like A, B, C .... Z. it is giving us numbers that i don't want the app to display. Here goes an example: 
screenshot from 2017-10-02 15-27-21

**Comment by eclecticexistential** [comment]
Understood. There is probably some logic that can be applied to disable the alphabet keycodes. Since the original num pad functionality issue is resolved, please merge this pull request into the repository and open a new issue for the alphabet bug. Doing so will help maintain organization within the repo.

**Comment by MohitChattlani** [comment]
Ok buddy.

**Pull request merged**
